version: "3.7"

services:
    database:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - "./.mysql-data/db:/var/lib/mysql"
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: userordersapp
        MYSQL_PASSWORD: Orders22899
        MYSQL_DATABASE: dashboard-orders
        MYSQL_USER: userordersapp
        
        
